/****************************************************************************
**
** Metadata for ShockwaveFlashObjects generated by dumpcpp from type library
** C:\WINDOWS\system32\Macromed\Flash\Flash6.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_SHOCKWAVEFLASHOBJECTS_NOINLINES
#include "shockwaveflashobjects.h"

using namespace ShockwaveFlashObjects;

static const uint qt_meta_data_ShockwaveFlashObjects__IShockwaveFlash[] = {

    // content:
    1,       // revision
    0,       // classname
    0, 0,    // classinfo
    54, 10,  // methods
    23, 280, // properties
    0, 0,    // enums/sets

    // signals: signature, parameters, type, tag, flags
    39, 78, 100, 101, 5, 102, 127, 132, 133, 5, 134, 160, 175, 176, 5,

    // slots: signature, parameters, type, tag, flags
    177, 184, 185, 186, 9, 187, 202, 203, 207, 9, 208, 223, 224, 228, 9, 229,
    239, 240, 241, 9, 242, 259, 268, 273, 9, 274, 295, 300, 308, 9, 309, 324,
    333, 334, 9, 335, 347, 348, 353, 9, 354, 377, 387, 388, 9, 389, 406, 415,
    416, 9, 417, 433, 434, 438, 9, 439, 446, 447, 448, 9, 449, 458, 459, 460, 9,
    461, 479, 489, 490, 9, 491, 521, 539, 540, 9, 541, 561, 569, 570, 9, 571,
    595, 611, 612, 9, 613, 630, 635, 636, 9, 637, 657, 668, 669, 9, 670, 690,
    701, 702, 9, 703, 725, 735, 736, 9, 737, 754, 763, 764, 9, 765, 779, 784,
    785, 9, 786, 800, 805, 806, 9, 807, 825, 831, 832, 9, 833, 850, 858, 859, 9,
    860, 876, 884, 885, 9, 886, 907, 916, 917, 9, 918, 937, 944, 945, 9, 946,
    967, 976, 977, 9, 978, 996, 1002, 1003, 9, 1004, 1022, 1032, 1033, 9, 1034,
    1063, 1074, 1075, 9, 1076, 1094, 1100, 1101, 9, 1102, 1131, 1153, 1154, 9,
    1155, 1162, 1163, 1164, 9, 1165, 1176, 1177, 1178, 9, 1179, 1203, 1219,
    1220, 9, 1221, 1249, 1262, 1263, 9, 1264, 1287, 1294, 1298, 9, 1299, 1322,
    1329, 1337, 9, 1338, 1364, 1380, 1388, 9, 1389, 1423, 1439, 1446, 9, 1447,
    1476, 1492, 1499, 9, 1500, 1524, 1540, 1541, 9, 1542, 1570, 1583, 1584, 9,
    1585, 1600, 1607, 1608, 9, 1609, 1643, 1665, 1666, 9, 1667, 1703, 1725,
    1726, 9, 1727, 1746, 1753, 1754, 9, 1755, 1765, 1772, 1773, 9,

    // properties: name, type, flags
    1774, 1784, 0x02015003, // int AlignMode
    1788, 1806, 0x0a015003, // QString AllowScriptAccess
    1814, 1822, 0x0a015003, // QString BGColor
    1830, 1846, 0x02015003, // int BackgroundColor
    1850, 1855, 0x0a015003, // QString Base
    1863, 1874, 0x01015003, // bool DeviceFont
    1879, 1890, 0x01015003, // bool EmbedMovie
    1895, 1905, 0x0a015003, // QString FlashVars
    1913, 1922, 0x02015003, // int FrameNum
    1926, 1931, 0x01015003, // bool Loop
    1936, 1941, 0x01015003, // bool Menu
    1946, 1952, 0x0a015003, // QString Movie
    1960, 1968, 0x01015003, // bool Playing
    1973, 1981, 0x02015003, // int Quality
    1985, 1994, 0x0a015003, // QString Quality2
    2002, 2013, 0x02005001, // int ReadyState
    2017, 2024, 0x0a015003, // QString SAlign
    2032, 2041, 0x0a015003, // QString SWRemote
    2049, 2055, 0x0a015003, // QString Scale
    2063, 2073, 0x02015003, // int ScaleMode
    2077, 2089, 0x02005001, // int TotalFrames
    2093, 2099, 0x0a015003, // QString WMode
    2107, 2115, 0x0a055003, // QString control

    0 // eod
};

static const char *qt_meta_stringdata_ShockwaveFlashObjects__IShockwaveFlash()
{
    static const char stringdata0[] = {
        "ShockwaveFlashObjects::IShockwaveFlash\0"
        "exception(int,QString,QString,QString)\0code,source,disc,"
        "help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*"
        ")\0name,argc,argv\0\0\0"
        "Back()\0\0\0\0CurrentFrame()\0\0int\0\0FlashVersion()"
        "\0\0int\0\0Forward()\0\0"
        "\0\0FrameLoaded(int)\0FrameNum\0bool\0\0GetVariable(QString)"
        "\0name\0QString\0\0GotoFrame(int)\0FrameNum\0\0\0IsPlaying()"
        "\0\0bool\0\0LoadMovie(int,QString)\0layer,url\0\0\0Pan(int,int,int)"
        "\0x,y,mode\0\0\0PercentLoaded()\0\0int\0\0Play()\0"
        "\0\0\0Rewind()\0\0\0\0SetAlignMode(int)"
        "\0AlignMode\0\0\0SetAllowScriptAccess(QString)"
        "\0AllowScriptAccess\0\0\0SetBGColor(QString)"
        "\0BGColor\0\0\0SetBackgroundColor(int)\0BackgroundColor\0\0\0SetBase("
        "QString)\0Base\0\0\0SetDeviceFont(bool)\0"
        "DeviceFont\0\0\0SetEmbedMovie(bool)\0EmbedMovie\0\0\0SetFlashVars("
        "QString)\0FlashVars\0\0\0SetFrameNum(int)\0FrameNum\0\0\0SetLoop(bool)"
        "\0Loop\0\0\0SetMenu(bool)\0Menu\0\0\0SetMovie(QString)"
        "\0Movie\0\0\0SetPlaying(bool)\0Playing\0"
        "\0\0SetQuality(int)\0Quality\0\0\0SetQuality2(QString)"
        "\0Quality2\0\0\0SetSAlign(QString)\0SAlign\0\0\0SetSWRemote(QString)"
        "\0SWRemote\0\0\0SetScale(QString)\0Scale\0\0\0SetScaleMode(int)"
        "\0ScaleMode\0\0\0SetVariable(QString,QString)\0"
        "name,value\0\0\0SetWMode(QString)\0WMode\0\0\0SetZoomRect(int,int,int,"
        "int)\0left,top,right,bottom\0\0\0Stop()\0\0\0\0StopPlay()"
        "\0\0\0\0TCallFrame(QString,int)\0target,FrameNum\0\0\0TCallLabel("
        "QString,QString)\0target,label\0\0\0"
        "TCurrentFrame(QString)\0target\0int\0\0TCurrentLabel(QString)"
        "\0target\0QString\0\0TGetProperty(QString,int)\0target,"
        "property\0QString\0\0TGetPropertyAsNumber(QString,int)\0target,"
        "property\0double\0\0TGetPropertyNum(QString,int)\0"
        "target,property\0double\0\0TGotoFrame(QString,int)\0target,"
        "FrameNum\0\0\0TGotoLabel(QString,QString)\0target,label\0\0\0TPlay("
        "QString)\0target\0\0\0TSetProperty(QString,int,QString)\0target,"
        "property,value\0\0\0TSetPropertyNum(QString,int,double)\0"
        "target,property,value\0\0\0TStopPlay(QString)\0target\0\0\0Zoom(int)"
        "\0factor\0\0\0"
        "AlignMode\0int\0AllowScriptAccess\0QString\0BGColor\0QString\0Backgrou"
        "ndColor\0int\0Base\0QString\0DeviceFont\0bool\0EmbedMovie\0bool\0Flash"
        "Vars\0"
        "QString\0FrameNum\0int\0Loop\0bool\0Menu\0bool\0Movie\0QString\0Playin"
        "g\0bool\0Quality\0int\0Quality2\0QString\0ReadyState\0int\0SAlign\0QSt"
        "ring\0SWRemote\0QString\0Scale\0QString\0ScaleMode\0int\0TotalFrames\0"
        "int\0WMode\0QString\0"
        "control\0QString\0"};
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IShockwaveFlash::staticMetaObject = {
    {&QObject::staticMetaObject,
     (const QByteArrayData *)
         qt_meta_stringdata_ShockwaveFlashObjects__IShockwaveFlash(),
     qt_meta_data_ShockwaveFlashObjects__IShockwaveFlash}};

void *IShockwaveFlash::qt_metacast(const char *_clname)
{
    if (!_clname)
        return 0;
    if (!strcmp(_clname,
                qt_meta_stringdata_ShockwaveFlashObjects__IShockwaveFlash()))
        return static_cast<void *>(const_cast<IShockwaveFlash *>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_ShockwaveFlashObjects__ShockwaveFlash[] = {

    // content:
    1,       // revision
    0,       // classname
    1, 10,   // classinfo
    57, 12,  // methods
    22, 297, // properties
    0, 0,    // enums/sets

    // classinfo: key, value
    38, 50,

    // signals: signature, parameters, type, tag, flags
    66, 93, 106, 107, 5, 108, 124, 136, 137, 5, 138, 162, 171, 172, 5, 173, 212,
    234, 235, 5, 236, 261, 266, 267, 5, 268, 294, 309, 310, 5,

    // slots: signature, parameters, type, tag, flags
    311, 318, 319, 320, 9, 321, 336, 337, 341, 9, 342, 357, 358, 362, 9, 363,
    373, 374, 375, 9, 376, 393, 402, 407, 9, 408, 429, 434, 442, 9, 443, 458,
    467, 468, 9, 469, 481, 482, 487, 9, 488, 511, 521, 522, 9, 523, 540, 549,
    550, 9, 551, 567, 568, 572, 9, 573, 580, 581, 582, 9, 583, 592, 593, 594, 9,
    595, 613, 623, 624, 9, 625, 655, 673, 674, 9, 675, 695, 703, 704, 9, 705,
    729, 745, 746, 9, 747, 764, 769, 770, 9, 771, 791, 802, 803, 9, 804, 824,
    835, 836, 9, 837, 859, 869, 870, 9, 871, 888, 897, 898, 9, 899, 913, 918,
    919, 9, 920, 934, 939, 940, 9, 941, 959, 965, 966, 9, 967, 984, 992, 993, 9,
    994, 1010, 1018, 1019, 9, 1020, 1041, 1050, 1051, 9, 1052, 1071, 1078, 1079,
    9, 1080, 1101, 1110, 1111, 9, 1112, 1130, 1136, 1137, 9, 1138, 1156, 1166,
    1167, 9, 1168, 1197, 1208, 1209, 9, 1210, 1228, 1234, 1235, 9, 1236, 1265,
    1287, 1288, 9, 1289, 1296, 1297, 1298, 9, 1299, 1310, 1311, 1312, 9, 1313,
    1337, 1353, 1354, 9, 1355, 1383, 1396, 1397, 9, 1398, 1421, 1428, 1432, 9,
    1433, 1456, 1463, 1471, 9, 1472, 1498, 1514, 1522, 9, 1523, 1557, 1573,
    1580, 9, 1581, 1610, 1626, 1633, 9, 1634, 1658, 1674, 1675, 9, 1676, 1704,
    1717, 1718, 9, 1719, 1734, 1741, 1742, 9, 1743, 1777, 1799, 1800, 9, 1801,
    1837, 1859, 1860, 9, 1861, 1880, 1887, 1888, 9, 1889, 1899, 1906, 1907, 9,

    // properties: name, type, flags
    1908, 1918, 0x02015003, // int AlignMode
    1922, 1940, 0x0a015003, // QString AllowScriptAccess
    1948, 1956, 0x0a015003, // QString BGColor
    1964, 1980, 0x02015003, // int BackgroundColor
    1984, 1989, 0x0a015003, // QString Base
    1997, 2008, 0x01015003, // bool DeviceFont
    2013, 2024, 0x01015003, // bool EmbedMovie
    2029, 2039, 0x0a015003, // QString FlashVars
    2047, 2056, 0x02015003, // int FrameNum
    2060, 2065, 0x01015003, // bool Loop
    2070, 2075, 0x01015003, // bool Menu
    2080, 2086, 0x0a015003, // QString Movie
    2094, 2102, 0x01015003, // bool Playing
    2107, 2115, 0x02015003, // int Quality
    2119, 2128, 0x0a015003, // QString Quality2
    2136, 2147, 0x02005001, // int ReadyState
    2151, 2158, 0x0a015003, // QString SAlign
    2166, 2175, 0x0a015003, // QString SWRemote
    2183, 2189, 0x0a015003, // QString Scale
    2197, 2207, 0x02015003, // int ScaleMode
    2211, 2223, 0x02005001, // int TotalFrames
    2227, 2233, 0x0a015003, // QString WMode

    0 // eod
};

static const char *qt_meta_stringdata_ShockwaveFlashObjects__ShockwaveFlash()
{
    static const char stringdata0[] = {
        "ShockwaveFlashObjects::ShockwaveFlash\0"
        "Interface 0\0IShockwaveFlash\0"
        "FSCommand(QString,QString)\0command,args\0\0\0OnProgress(int)"
        "\0percentDone\0\0\0OnReadyStateChange(int)\0newState\0\0\0exception("
        "int,QString,QString,QString)\0code,source,disc,"
        "help\0\0\0propertyChanged(QString)\0"
        "name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
        "Back()\0\0\0\0CurrentFrame()\0\0int\0\0FlashVersion()"
        "\0\0int\0\0Forward()\0\0\0\0FrameLoaded(int)"
        "\0FrameNum\0bool\0\0GetVariable(QString)\0name\0QString\0\0GotoFrame("
        "int)\0FrameNum\0"
        "\0\0IsPlaying()\0\0bool\0\0LoadMovie(int,QString)\0layer,url\0\0\0Pan("
        "int,int,int)\0x,y,mode\0\0\0PercentLoaded()\0\0int\0\0Play()"
        "\0\0\0\0Rewind()\0\0\0\0SetAlignMode(int)"
        "\0AlignMode\0\0\0SetAllowScriptAccess(QString)\0AllowScriptAccess\0"
        "\0\0SetBGColor(QString)\0BGColor\0\0\0SetBackgroundColor(int)"
        "\0BackgroundColor\0\0\0SetBase(QString)\0Base\0\0\0SetDeviceFont(bool)"
        "\0DeviceFont\0\0\0SetEmbedMovie(bool)\0EmbedMovie\0\0\0SetFlashVars("
        "QString)\0FlashVars\0\0\0SetFrameNum(int)\0"
        "FrameNum\0\0\0SetLoop(bool)\0Loop\0\0\0SetMenu(bool)"
        "\0Menu\0\0\0SetMovie(QString)\0Movie\0\0\0SetPlaying(bool)"
        "\0Playing\0\0\0SetQuality(int)\0Quality\0\0\0SetQuality2(QString)"
        "\0Quality2\0\0\0SetSAlign(QString)\0SAlign\0\0\0SetSWRemote(QString)\0"
        "SWRemote\0\0\0SetScale(QString)\0Scale\0\0\0SetScaleMode(int)"
        "\0ScaleMode\0\0\0SetVariable(QString,QString)\0name,"
        "value\0\0\0SetWMode(QString)\0WMode\0\0\0SetZoomRect(int,int,int,int)"
        "\0left,top,right,bottom\0\0\0Stop()\0\0\0\0StopPlay()\0"
        "\0\0\0TCallFrame(QString,int)\0target,FrameNum\0\0\0TCallLabel("
        "QString,QString)\0target,label\0\0\0TCurrentFrame(QString)"
        "\0target\0int\0\0TCurrentLabel(QString)"
        "\0target\0QString\0\0TGetProperty(QString,int)\0target,property\0"
        "QString\0\0TGetPropertyAsNumber(QString,int)\0target,"
        "property\0double\0\0TGetPropertyNum(QString,int)\0target,"
        "property\0double\0\0TGotoFrame(QString,int)\0target,"
        "FrameNum\0\0\0TGotoLabel(QString,QString)\0target,label\0"
        "\0\0TPlay(QString)\0target\0\0\0TSetProperty(QString,int,QString)"
        "\0target,property,value\0\0\0TSetPropertyNum(QString,int,double)"
        "\0target,property,value\0\0\0TStopPlay(QString)\0target\0\0\0Zoom(int)"
        "\0factor\0\0\0"
        "AlignMode\0"
        "int\0AllowScriptAccess\0QString\0BGColor\0QString\0BackgroundColor\0in"
        "t\0Base\0QString\0DeviceFont\0bool\0EmbedMovie\0bool\0FlashVars\0QStri"
        "ng\0FrameNum\0int\0Loop\0bool\0Menu\0bool\0Movie\0QString\0Playing\0bo"
        "ol\0Quality\0int\0"
        "Quality2\0QString\0ReadyState\0int\0SAlign\0QString\0SWRemote\0QString"
        "\0Scale\0QString\0ScaleMode\0int\0TotalFrames\0int\0WMode\0QString\0"};
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject ShockwaveFlash::staticMetaObject = {
    {&QWidget::staticMetaObject,
     (const QByteArrayData *)
         qt_meta_stringdata_ShockwaveFlashObjects__ShockwaveFlash(),
     qt_meta_data_ShockwaveFlashObjects__ShockwaveFlash}};

void *ShockwaveFlash::qt_metacast(const char *_clname)
{
    if (!_clname)
        return 0;
    if (!strcmp(_clname,
                qt_meta_stringdata_ShockwaveFlashObjects__ShockwaveFlash()))
        return static_cast<void *>(const_cast<ShockwaveFlash *>(this));
    return QAxWidget::qt_metacast(_clname);
}

static const uint qt_meta_data_ShockwaveFlashObjects__FlashProp[] = {

    // content:
    1,     // revision
    0,     // classname
    0, 0,  // classinfo
    3, 10, // methods
    0, 0,  // properties
    0, 0,  // enums/sets

    // signals: signature, parameters, type, tag, flags
    33, 72, 94, 95, 5, 96, 121, 126, 127, 5, 128, 154, 169, 170, 5,

    // slots: signature, parameters, type, tag, flags

    0 // eod
};

static const char *qt_meta_stringdata_ShockwaveFlashObjects__FlashProp()
{
    static const char stringdata0[] = {
        "ShockwaveFlashObjects::FlashProp\0"
        "exception(int,QString,QString,QString)\0code,source,disc,"
        "help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*"
        ")\0name,argc,argv\0\0\0"
        ""};
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject FlashProp::staticMetaObject = {
    {&QObject::staticMetaObject,
     (const QByteArrayData *)
         qt_meta_stringdata_ShockwaveFlashObjects__FlashProp(),
     qt_meta_data_ShockwaveFlashObjects__FlashProp}};

void *FlashProp::qt_metacast(const char *_clname)
{
    if (!_clname)
        return 0;
    if (!strcmp(_clname, qt_meta_stringdata_ShockwaveFlashObjects__FlashProp()))
        return static_cast<void *>(const_cast<FlashProp *>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_ShockwaveFlashObjects__FlashObjectInterface[] = {

    // content:
    1,     // revision
    0,     // classname
    1, 10, // classinfo
    3, 12, // methods
    0, 0,  // properties
    0, 0,  // enums/sets

    // classinfo: key, value
    44, 56,

    // signals: signature, parameters, type, tag, flags
    78, 117, 139, 140, 5, 141, 166, 171, 172, 5, 173, 199, 214, 215, 5,

    // slots: signature, parameters, type, tag, flags

    0 // eod
};

static const char *
qt_meta_stringdata_ShockwaveFlashObjects__FlashObjectInterface()
{
    static const char stringdata0[] = {
        "ShockwaveFlashObjects::FlashObjectInterface\0"
        "Interface 0\0IFlashObjectInterface\0"
        "exception(int,QString,QString,QString)\0code,source,disc,"
        "help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*"
        ")\0name,argc,argv\0\0\0"
        ""};
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject FlashObjectInterface::staticMetaObject = {
    {&QObject::staticMetaObject,
     (const QByteArrayData *)
         qt_meta_stringdata_ShockwaveFlashObjects__FlashObjectInterface(),
     qt_meta_data_ShockwaveFlashObjects__FlashObjectInterface}};

void *FlashObjectInterface::qt_metacast(const char *_clname)
{
    if (!_clname)
        return 0;
    if (!strcmp(
            _clname,
            qt_meta_stringdata_ShockwaveFlashObjects__FlashObjectInterface()))
        return static_cast<void *>(const_cast<FlashObjectInterface *>(this));
    return QAxObject::qt_metacast(_clname);
}
