function s=a3parseresults(d)
% function [trials,stimuli,correctanswer,corrector,useranswers]=a3parseresults(d)
% parse results generated by the parse output mode of apexresult.xsl
% d is cell array of lines

I=strmatch('Header=', d);
if (isempty(I))
    error('Cannot parse data, you can try rerunning the xslt transformation');
end

%% parse header
fields=amt_strsplit(d{I}(8:end), ';');

S=strmatch('START', d);
if (isempty(S))
    error('Cannot parse data');
end

E=strmatch('END', d);
if (isempty(E))
    error('Cannot parse data');
end

len=E-S-1;

%s=struct;

for l=1:len
    t=amt_strsplit(d{l+S}, ';');

    if (length(t) ~= length(fields))
        error('Header does not match data');
    end
    tempstruct=struct;
    for i=1:length(t)
        tempstruct=setfield(tempstruct, fields{i}, t{i});
    end
    s(l)=tempstruct;

%     trials{l}=t{1};
%     stimuli{l}=t{2};
%     correctanswer{l}=t{3};
%     if (strcmp(t{4},'true'))
%         corrector(l)=1;
%     end
%     useranswers{l}=t{5};
end
