moc -o ./moc/moc_fileselector.cpp fileselector.h
moc -o ./moc/moc_qwtplot.cpp qwtplot.h
moc -o ./moc/moc_scrollbar.cpp scrollbar.h
moc -o ./moc/moc_scrollzoomer.cpp scrollzoomer.h
moc -o ./moc/moc_slideredit.cpp slideredit.h
moc -o ./moc/moc_userinputbase.cpp userinputbase.h
moc -o ./moc/moc_msgwindow.cpp msgwindow.h
moc -o ./moc/moc_msghandler.cpp ../appcore/qt_msghandler.h
moc -o ./moc/moc_minidumpgui.cpp minidumpgui.h
