/* File generated by genversion.sh, do not modify manually */
#define APEX_VERSION "3.0.3"
#define APEX_VERSION_MAJOR 3
#define APEX_VERSION_MINOR 0
#define APEX_VERSION_FLOAT 3.0
#define SVN_REVISION "$Rev$"
#define SCHEMA_VERSION "3.0.3"
#define EXPERIMENT_NAMESPACE "http://med.kuleuven.be/exporl/apex/3.0.3/experiment"
